#LIVE## DO NOT EDIT THIS FILE - edit the master and reinstall.
#LIVE## (/tmp/crontab.8223 installed on Fri Mar  2 14:08:07 2007)
#LIVE## (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
#LIVE#MARK*/1 6-20 * * *  /home/ceubeplive/chd3backend/partition.sh
#LIVE*/1 6-20 * * *  /home/ceubeplive/chd3backend/invoice.sh
#LIVE*/1 6-20 * * *  /home/ceubeplive/chd3backend/images.sh
#LIVE*/1 6-20 * * *  /home/ceubeplive/chd3backend/reports.sh
#LIVE*/1 6-20 * * *  /home/ceubeplive/chd3backend/packages.sh
#LIVE*/1 6-20 * * *  /home/ceubeplive/chd3backend/scud.sh
#LIVE*/1 6-20 * * *  /home/ceubeplive/chd3backend/fiche.sh
#LIVE#
#LIVE*/1 6-20 * * *  /home/ceubeplive/chd3backend/jobsheet.sh
#LIVE*/5 6-20 * * *  /home/ceubeplive/chd3backend/internal.sh
#LIVE#
#LIVE##Print only on Tux2
#LIVE*/1 6-20 * * *  /home/ceubeplive/chd3backend/print.sh
#LIVE*/1 6-20 * * *  /home/ceubeplive/chd3backend/email.sh
#LIVE#
#LIVE*/1 6-20 * * *  /home/ceubeplive/chd3backend/fax.sh
#LIVE*/5 6-20 * * *  /home/ceubeplive/chd3backend/faxStatus.sh
#LIVE## SR - amend  cron due to session problems
#LIVE#*/10 0-23 * * *  /home/ceubeplive/chd3backend/weedall.sh
#LIVE#
#LIVE## Dump yesterdays order details
#LIVE0 5 * * 2-6 /home/ceubeplive/publ_cust/dump_orderDetail.sh >/tmp/orderDetail.out 2>&1
#LIVE#
#LIVE## Perform IMPORT of PUBL Customer Database into CEU Customer Table
#LIVE25 7 * * 0-6 /home/ceubeplive/publ_cust/process_new_publ_dump.sh /home/custupdt/customer_info >/tmp/results-7-25 2>&1
#LIVE#
#LIVE#SR*/5 8-17 * * 1-5 /home/ceubeplive/chd3backend/printerQueueChecker.sh
#LIVE#
#LIVE#SR0 0 * * 0 > /home/ceubeplive/backend.log
#LIVE#
#LIVE## send a list of cert orders to cert copies section as a double check
#LIVE
#LIVE#SR5 10,12,14,16,18 * * 1-5 /home/ceubeplive/chd3backend/checkCerts.sh
#LIVE#DC0 8-18 * * 1-5 /home/ceubeplive/chd3backend/SameDaycheckCerts.sh
#LIVE1 8-18 * * 1-5 /home/ceubeplive/chd3backend/StandardcheckCerts.sh
#LIVE
#LIVE0 8,9,10,11,12,13,14,15,16,17,18 * * 1-5 /home/ceubeplive/chd3backend/getCEUFicheOrders.sh
#LIVE#sr - start INC0279140
#LIVE#20 15 * * 1-5 /home/ceubeplive/chd3backend/getCEUFicheOrders.sh
#LIVE#40 15 * * 1-5 /home/ceubeplive/chd3backend/getCEUFicheOrders.sh
#LIVE#sr - end INC0279140
#LIVE#
#LIVE##Cleanup Jobs
#LIVE5 1 * * * find /mnt/ceu/ais/post -path /mnt/ceu/ais/post/.snapshot/ -prune -o -type f -ctime +4 -exec rm -f {} \;
#LIVE10 1 * * * find /mnt/ceu/ais/fax -path /mnt/ceu/ais/fax/.snapshot/ -prune -o -type f -ctime +4 -exec rm -f {} \;
#LIVE15 1 * * * find /mnt/ceu/ais/email -path /mnt/ceu/ais/email/CEU/.snapshot/ -prune -o -type f -ctime +4 -exec rm -f {} \;
#LIVE20 1 * * * find /mnt/ceu/ais/online -path /mnt/ceu/ais/online/.snapshot/ -prune -o -type f -ctime +1 -exec rm -f {} \;
#LIVE#

#STAGING#### min hour day month weekday
#STAGING###
#STAGING#### Partition orders into product groups every minute
#STAGING###
#STAGING*/1 7-23 * * *     /home/ceupreprodbeptest/chd3backend/partition.sh
#STAGING###
#STAGING#### Generate reports mon-sat 7am->midnight every minute
#STAGING####
#STAGING*/1 7-23 * * *  /home/ceupreprodbeptest/chd3backend/reports.sh
#STAGING###
#STAGING#### Generate images mon-sat 7am->midnight
#STAGING####
#STAGING*/1 7-23 * * *  /home/ceupreprodbeptest/chd3backend/images.sh
#STAGING###
#STAGING#### Generate packages mon-sat 7am->midnight
#STAGING####
#STAGING*/1 7-23 * * *  /home/ceupreprodbeptest/chd3backend/packages.sh
#STAGING###
#STAGING#### Generate scud mon-sat 7am->midnight
#STAGING####
#STAGING*/1 7-23 * * *  /home/ceupreprodbeptest/chd3backend/scud.sh
#STAGING###
#STAGING#### Generate fiche mon-sat 7am->midnight
#STAGING####
#STAGING*/1 7-23 * * *  /home/ceupreprodbeptest/chd3backend/fiche.sh
#STAGING####
#STAGING#### Generate invoices mon-sat 7am->midnight (used for Certified Copies etc)
#STAGING####
#STAGING*/1 7-23 * * *  /home/ceupreprodbeptest/chd3backend/invoice.sh
#STAGING###
#STAGING### Generate jobsheets mon-sat 7am->midnight (used for Certified Copies etc)
#STAGING####
#STAGING*/1 7-23 * * *  /home/ceupreprodbeptest/chd3backend/jobsheet.sh
#STAGING#### Generate (charge) monitor orders mon-sat 7am->midnight
#STAGING####
#STAGING*/1 7-23 * * *  /home/ceupreprodbeptest/chd3backend/monitor.sh
#STAGING###
#STAGING#### Do monitor Matching process mon-sat every 10 mins
#STAGING#### (This should only pick up matches once - but for testing purposes......)
#STAGING####
#STAGING*/10 7-23 * * *  /home/ceupreprodbeptest/chd3backend/monitorMatch.sh
#STAGING##
#STAGING### Dispatch Faxes mon-sat 7am->midnight
#STAGING###
#STAGING*/1 7-23 * * *  /home/ceupreprodbeptest/chd3backend/fax.sh
#STAGING##
#STAGING### Dispatch Emails mon-sat 7am->midnight
#STAGING###
#STAGING*/1 7-23 * * *  /home/ceupreprodbeptest/chd3backend/email.sh
#STAGING*/1 7-23 * * *  /home/ceupreprodbeptest/chd3backend/print.sh
#STAGING##
#STAGING### Scan for and record Fax delivery status to CH report dir and to Database
#STAGING##
#STAGING*/5 7-23 * * *  /home/ceupreprodbeptest/chd3backend/faxStatus.sh
#STAGING##
#STAGING## Scan for internal-delivery products (Currently Cert Copies etc)
#STAGING###
#STAGING*/5 7-23 * * *  /home/ceupreprodbeptest/chd3backend/internal.sh
#STAGING##
#STAGING### WEEDING
#STAGING###
#STAGING#*/5 7-23 * * *  /home/ceupreprodbeptest/chd3backend/weedall.sh
#STAGING###
#STAGING#####You have new mail in /var/spool/mail/ceupreprodbeptest
#STAGING###
